/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Business.Employee;

/**
 *
 * @author ymayank97
 */
public class Employee {
 
    private String employeeName;
    private int empID;
    private static int count=1;
    //Employee class constructor used to calculate autogenerated empID 
    public Employee(){
        empID=count;
        count++;
    }

    public int getEmpID() {
        return empID;
    }

    public void setEmpID(int id) {
        this.empID = id;
    }
    
    public String getEmployeeName() {
        return employeeName;
    }

    public void setEmployeeName(String name) {
        this.employeeName = name;
    }
    @Override
    public String toString(){
        return employeeName;
    }
    
}